version: '3.8'

networks:
  corp:
    driver: bridge

services:
  pstgresdb:
    container_name: postgresdb
    image: postgres:${ESKIMAL_POSTGRES_VERSION}
    restart: always
    ports:
      - ${ESKIMAL_POSTGRES_EXPOSE_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${ESKIMAL_POSTGRES_PASSWORD?:error}
      ESKIMAL_POSTGRES_VERSION: ${ESKIMAL_POSTGRES_VERSION?:error}
      ESKIMAL_POSTGRES_PASSWORD: ${ESKIMAL_POSTGRES_PASSWORD?:error}
      ESKIMAL_POSTGRES_EXPOSE_PORT: ${ESKIMAL_POSTGRES_EXPOSE_PORT?:error}

  eskimal:
    container_name: eskimal
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/eskimal/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: eskimal:nx-dev
    ports:
      - ${ESKIMAL_EXPOSE_PORT}:4939
    env_file:
      - .env
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      ESKIMAL_EXPOSE_PORT: ${ESKIMAL_EXPOSE_PORT?:error}
    networks:
      - corp
    restart: on-failure

  persona:
    container_name: persona
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/persona/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: persona:nx-dev
    ports:
      - ${PERSONA_EXPOSE_PORT}:80
    env_file:
      - .env
    environment:
      NODE_ENV: 'development'
      PORT: 4900
      PERSONA_EXPOSE_PORT: ${PERSONA_EXPOSE_PORT?:error}
    networks:
      - corp
    restart: on-failure
